### PR TITLE
Dating app logo

### PR DESCRIPTION
**Pull request by pixobia**

### CODE REVIEW

**Comment by Pulkiteleven** [comment]
Try making the logo a bit more minimal, and without text, and don't include heart in icon, because there exists no heart logo in a dating app(in most cases as in Tinder). So try to make logo a bit more better.

**Comment by pixobia** [comment]
but most of the design are having heart sir..

**Comment by pixobia** [comment]
i wanna have try another but it will have love symbols,if you are ok with it i will start preparing it..

**Comment by Pulkiteleven** [comment]
> i wanna have try another but it will have love symbols,if you are ok with it i will start preparing it..

Yes you can create it..

**Comment by RajatBhaskare7** [comment]
@Pulkiteleven check this request

**Pull request merged**
